package com.vankhai.weather.model;

public enum Condition {
    Sunny,
    Clear,
    PartlyCloudy,
    Overcast, Mist,
    PatchyRainPossible,
    PatchySnowPossible,
    PatchySleetPossible,
    PatchyFreezingDrizzlePossible,
    ThunderyOutbreaksPossible,
    BlowingSnow,
    Blizzard,
    Fog,
    FreezingFog,
    PatchyLightDrizzle,
    LightDrizzle,
    FreezingDrizzle,
    HeavyFreezingDrizzle,
    PatchyLightRain,
    LightRain,
    ModerateRainAtTimes,
    ModerateRain,
    HeavyRainAtTimes,
    HeavyRain, LightFreezingRain,
    ModerateOrHeavyFreezingRain,
    LightSleet,
    ModerateOrHeavySleet,
    PatchyLightSnow,
    LightSnow,
    PatchyModerateSnow,
    ModerateSnow,
    PatchyHeavySnow,
    HeavySnow,
    IcePellets,
    LightRainShower,
    ModerateOrHeavyRainShower,
    TorrentialRainShower,
    LightSleetShowers,
    ModerateOrHeavySleetShowers,
    LightSnowShowers,
    ModerateOrHeavySnowShowers,
    LightShowersOfIcePellets,
    ModerateOrHeavyShowersOfIcePellets,
    PatchyLightRainWithThunder,
    ModerateOrHeavyRainWithThunder,
    PatchyLightSnowWithThunder,
    ModerateOrHeavySnowWithThunder
}
